/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManufacturerWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SecondaryTestingKit;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.PrimaryTestingKit;
import Business.WorkQueue.ManufactureringTestWorkrequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author Abhilash Wase
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
     private EcoSystem system;
     private UserAccount account;
     private Enterprise enterprise;
     //RecyclableWaste recyclableWaste = new PrimaryTestingKit();
    //private LabTestWorkRequest request;
   /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ProcessWorkRequestJPanel(JPanel userProcessContainer,EcoSystem system,UserAccount account,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.account = account;
        this.enterprise= enterprise;
       
         jLabel3.setVisible(false);
         jLabel4.setVisible(false);
         jLabel5.setVisible(false);
         jLabel6.setVisible(false);
         jLabel7.setVisible(false);
            
          jTextField1.setVisible(false);
          jTextField2.setVisible(false);
          jTextField3.setVisible(false);
          jTextField4.setVisible(false);
          jTextField5.setVisible(false);  
          processToLabJText.setEnabled(false);
          processToLabJText.setVisible(false);
          submitJButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitJButton = new javax.swing.JButton();
        manufacturingComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        processToLabJText = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        submitJButton.setBackground(new java.awt.Color(0, 102, 204));
        submitJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(255, 255, 255));
        submitJButton.setText("Submit Data");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        manufacturingComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please choose from the below", "Primary Testing Kit", "Secondary Testing Kit", "Waste Quantity" }));
        manufacturingComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacturingComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Please Select Kit Type : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("jLabel7");

        processToLabJText.setBackground(new java.awt.Color(0, 102, 204));
        processToLabJText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        processToLabJText.setForeground(new java.awt.Color(255, 255, 255));
        processToLabJText.setText("Process To Lab");
        processToLabJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processToLabJTextActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText(" x");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17))
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("MANUFACTURING DATA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel8)
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(manufacturingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(submitJButton)
                        .addGap(18, 18, 18)
                        .addComponent(processToLabJText)
                        .addGap(319, 319, 319))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(manufacturingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(processToLabJText)
                    .addComponent(submitJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );
    }// </editor-fold>//GEN-END:initComponents
    static boolean isNumberValid(String number)
    {
        String regex = "[\\\\s]*[0-9]*[0-9]+";
        return number.matches(regex);
    }
    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
       jTextField1.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel3.setForeground(Color.BLACK);
        
        jTextField2.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel4.setForeground(Color.BLACK);
        
        jTextField3.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel5.setForeground(Color.BLACK);
        
        jTextField4.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel6.setForeground(Color.BLACK);
        
        jTextField5.setBorder(new LineBorder(new Color(128,128,128)));
        jLabel7.setForeground(Color.BLACK);
        
        if(manufacturingComboBox.getSelectedIndex()==3)
        {
            if(isNumberValid(jTextField1.getText()) == false || jTextField1.getText() == null || jTextField1.getText().equals(""))
            {
                jTextField1.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel3.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel3.getText());
                return;
            }
        }
        else if(manufacturingComboBox.getSelectedIndex()==2){
            if(isNumberValid(jTextField1.getText()) == false || jTextField1.getText() == null || jTextField1.getText().equals(""))
            {
                jTextField1.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel3.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel3.getText());
                return;
            }
            else if(isNumberValid(jTextField2.getText()) == false || jTextField2.getText() == null || jTextField2.getText().equals(""))
            {
                jTextField2.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel4.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel4.getText());
                return;
            }
            else if(isNumberValid(jTextField3.getText()) == false || jTextField3.getText() == null || jTextField3.getText().equals(""))
            {
                jTextField3.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel5.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel5.getText());
                return;
            }
            else if(isNumberValid(jTextField4.getText()) == false || jTextField4.getText() == null || jTextField4.getText().equals(""))
            {
                jTextField4.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel6.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel6.getText());
                return;
            }
            else if(isNumberValid(jTextField5.getText()) == false || jTextField5.getText() == null || jTextField5.getText().equals(""))
            {
                jTextField5.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel7.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel7.getText());
                return;
            }
        }
        if(manufacturingComboBox.getSelectedIndex()==1)
        {
            if(isNumberValid(jTextField1.getText()) == false || jTextField1.getText() == null || jTextField1.getText().equals(""))
            {
                jTextField1.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel3.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel3.getText());
                return;
            }
            else if(isNumberValid(jTextField2.getText()) == false || jTextField2.getText() == null || jTextField2.getText().equals(""))
            {
                jTextField2.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel4.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel4.getText());
                return;
            }
            else if(isNumberValid(jTextField3.getText()) == false || jTextField3.getText() == null || jTextField3.getText().equals(""))
            {
                jTextField3.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel5.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel5.getText());
                return;
            }
            else if(isNumberValid(jTextField4.getText()) == false || jTextField4.getText() == null || jTextField4.getText().equals(""))
            {
                jTextField4.setBorder(BorderFactory.createLineBorder(Color.RED));
                jLabel6.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Please enter a valid number for "+jLabel6.getText());
                return;
            }
        }
        
        ArrayList<WorkRequest> result = system.getWorkQueue().getWorkRequestList();
        ManufactureringTestWorkrequest manufactureringTestWorkrequest=null;
       if(result==null || result.isEmpty()){
           manufactureringTestWorkrequest = new ManufactureringTestWorkrequest();
          result.add(manufactureringTestWorkrequest);
       }
       
       for (int i=0; i<result.size();i++) {
          manufactureringTestWorkrequest = (ManufactureringTestWorkrequest) result.get(i);
        if(manufacturingComboBox.getSelectedIndex()==3){
          double decomposableQuantity = Double.parseDouble(jTextField1.getText());
          decomposableQuantity = decomposableQuantity+manufactureringTestWorkrequest.getDecomposableQuantity();
          if(Integer.parseInt(jTextField1.getText())==0){
            JOptionPane.showMessageDialog(null, "Please enter a value greater than 0");
            return;
        }
          manufactureringTestWorkrequest.setDecomposableQuantity(decomposableQuantity);
          manufactureringTestWorkrequest.setKitType("Decomposing waste");
          JOptionPane.showMessageDialog(null, "Decomposing  waste added Succesfully");
          jTextField1.setText("");
          return;
        }
        else if(manufacturingComboBox.getSelectedIndex()==2){
            int numberOfThermometers = Integer.parseInt(jTextField1.getText());
            int numberOfSphygmomanometer = Integer.parseInt(jTextField2.getText());
            int numberOfGlucoseMeter = Integer.parseInt(jTextField3.getText());
            int numberOfStethoscopes = Integer.parseInt(jTextField4.getText());
            int numberOfMasks = Integer.parseInt(jTextField5.getText());
            
            if(numberOfThermometers==0&&numberOfSphygmomanometer==0&&numberOfGlucoseMeter==0&&numberOfStethoscopes==0&&numberOfMasks==0){
            JOptionPane.showMessageDialog(null, "Please enter a value greater than 0");
            return;
            }
            
            SecondaryTestingKit secondaryTestingKit = manufactureringTestWorkrequest.getSecondaryTestingKit();
            if(secondaryTestingKit==null){
                secondaryTestingKit = new SecondaryTestingKit();
            }
            numberOfThermometers = numberOfThermometers+((String.valueOf(secondaryTestingKit.getNumberOfThermometers()))==null?0:secondaryTestingKit.getNumberOfThermometers());
            secondaryTestingKit.setNumberOfThermometers(numberOfThermometers);
            
            numberOfSphygmomanometer = numberOfSphygmomanometer+(String.valueOf(secondaryTestingKit.getNumberOfSphygmomanometer())==null?0:secondaryTestingKit.getNumberOfSphygmomanometer());
            secondaryTestingKit.setNumberOfSphygmomanometer(numberOfSphygmomanometer);
            
            numberOfGlucoseMeter = numberOfGlucoseMeter+(String.valueOf(secondaryTestingKit.getNumberOfGlucoseMeter())==null?0:secondaryTestingKit.getNumberOfGlucoseMeter());
            secondaryTestingKit.setNumberOfGlucoseMeter(numberOfGlucoseMeter);
            
            numberOfStethoscopes = numberOfStethoscopes+(String.valueOf(secondaryTestingKit.getNumberOfStethoscopes())==null?0:secondaryTestingKit.getNumberOfStethoscopes());
            secondaryTestingKit.setNumberOfStethoscopes(numberOfStethoscopes);
            
            numberOfMasks =numberOfMasks+(String.valueOf(secondaryTestingKit.getNumberOfMasks())==null?0:secondaryTestingKit.getNumberOfMasks());
            secondaryTestingKit.setNumberOfMasks(numberOfMasks);
            
            manufactureringTestWorkrequest.setSecondaryTestingKit(secondaryTestingKit);
            JOptionPane.showMessageDialog(null, "Secondary Testing Kits added Succesfully");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
             return;
        }
       }
       for (Organization labOrganization : enterprise.getOrganizationDirectory().getOrganizationList()) {
             ArrayList<WorkRequest> labTestWorklist = labOrganization.getWorkQueue().getWorkRequestList();
               LabTestWorkRequest labTestWorkRequest = null;
                if(labTestWorklist==null || labTestWorklist.isEmpty()){
                  labTestWorkRequest = new LabTestWorkRequest();
                  labTestWorklist.add(labTestWorkRequest);
                }
          for(int i=0; i<labTestWorklist.size();i++){  
                labTestWorkRequest = (LabTestWorkRequest)labTestWorklist.get(i);
           if(manufacturingComboBox.getSelectedIndex()==1){
            int numberOfThroatSwab = Integer.parseInt(jTextField1.getText());
            int numberOfNasopharyngealSwab = Integer.parseInt(jTextField2.getText());
            int numberOfPCRMachine = Integer.parseInt(jTextField3.getText());
            int numberOfECGMachine = Integer.parseInt(jTextField4.getText());
            
            if(numberOfThroatSwab==0&&numberOfNasopharyngealSwab==0&&numberOfPCRMachine==0&&numberOfECGMachine==0){
            JOptionPane.showMessageDialog(null, "Please enter a value greater than 0");
            return;
            }
            
            PrimaryTestingKit primaryTestingKit = new PrimaryTestingKit();
            primaryTestingKit.setNumberOfThroatSwab(numberOfThroatSwab);
            primaryTestingKit.setNumberOfNasopharyngealSwab(numberOfNasopharyngealSwab);
            primaryTestingKit.setNumberOfPCRMachine(numberOfPCRMachine);
            primaryTestingKit.setNumberOfECGMachine(numberOfECGMachine);
            
            
            numberOfThroatSwab = ((String.valueOf(primaryTestingKit.getNumberOfThroatSwab()))==null?0:primaryTestingKit.getNumberOfThroatSwab());
            primaryTestingKit.setNumberOfThroatSwab(numberOfThroatSwab);
            
            numberOfNasopharyngealSwab = ((String.valueOf(primaryTestingKit.getNumberOfNasopharyngealSwab()))==null?0:primaryTestingKit.getNumberOfNasopharyngealSwab());
            primaryTestingKit.setNumberOfNasopharyngealSwab(numberOfNasopharyngealSwab);
            
            numberOfPCRMachine = ((String.valueOf(primaryTestingKit.getNumberOfPCRMachine()))==null?0:primaryTestingKit.getNumberOfPCRMachine());
            primaryTestingKit.setNumberOfPCRMachine(numberOfPCRMachine);
            
            numberOfECGMachine = ((String.valueOf(primaryTestingKit.getNumberOfECGMachine()))==null?0:primaryTestingKit.getNumberOfECGMachine());
            primaryTestingKit.setNumberOfECGMachine(numberOfECGMachine);
            
            primaryTestingKit.setStatus("Pending");
            
            labTestWorkRequest.setPrimaryTestingKit(primaryTestingKit);
            labTestWorkRequest.setMessage("message");
            labTestWorkRequest.setSender(account);
            labTestWorkRequest.setStatus("Sent");

            JOptionPane.showMessageDialog(null, "Primary Testing Kits added Succesfully");
//            jTextField1.setEnabled(false);
//            jTextField2.setEnabled(false);
//            jTextField3.setEnabled(false);
//            jTextField4.setEnabled(false);
//            jTextField5.setEnabled(false);
            submitJButton.setEnabled(false);
            processToLabJText.setEnabled(true);
             
         }return;
        }
        }
       
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void manufacturingComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacturingComboBoxActionPerformed
        if(manufacturingComboBox.getSelectedIndex()==3){
            jLabel3.setVisible(true);
            jLabel3.setText("Quantity(in lbs):");
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            processToLabJText.setVisible(false);
            submitJButton.setVisible(true);
            submitJButton.setEnabled(true);
            
          jTextField1.setVisible(true);
          jTextField1.setText("");
          jTextField2.setVisible(false);
          jTextField2.setText("");
          jTextField3.setVisible(false);
          jTextField3.setText("");
          jTextField4.setVisible(false);
          jTextField4.setText("");
          jTextField5.setVisible(false); 
          jTextField5.setText("");
          
        }
        else if(manufacturingComboBox.getSelectedIndex()==2){
            jLabel3.setVisible(true);
            jLabel3.setText("Number Of Thermometers");
            jLabel4.setVisible(true);
            jLabel4.setText("Number Of Sphygmomanometer");
            jLabel5.setVisible(true);
            jLabel5.setText("Number Of Glucosemeter");
            jLabel6.setVisible(true);
            jLabel6.setText("Number Of Stethoscopes");
            jLabel7.setVisible(true);
            jLabel7.setText("Number Of Masks");
            processToLabJText.setVisible(false);
            submitJButton.setVisible(true);
            submitJButton.setEnabled(true);
            
            jTextField1.setVisible(true);
            jTextField1.setText("");
            jTextField2.setVisible(true);
            jTextField2.setText("");
            jTextField3.setVisible(true);
            jTextField3.setText("");
            jTextField4.setVisible(true);
            jTextField4.setText("");
            jTextField5.setVisible(true);
            jTextField5.setText("");
            
        }
        else if(manufacturingComboBox.getSelectedIndex()==1){
            jLabel3.setVisible(true);
            jLabel3.setText("Number Of Throat Swab");
            jLabel4.setVisible(true);
            jLabel4.setText("Number Of Nasopharyngeal Swab");
            jLabel5.setVisible(true);
            jLabel5.setText("Number Of PCR Machine");
            jLabel6.setVisible(true);
            jLabel6.setText("Number Of ECG Machine");
            jLabel7.setVisible(false);
            processToLabJText.setVisible(true);
            submitJButton.setVisible(true);
           
            jTextField1.setVisible(true);
            jTextField1.setText("");
            jTextField2.setVisible(true);
            jTextField2.setText("");
            jTextField3.setVisible(true);
            jTextField3.setText("");
            jTextField4.setVisible(true);
            jTextField4.setText("");
            jTextField5.setVisible(false);
            jTextField5.setText("");
            
        }
        else{
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            submitJButton.setVisible(false);
            processToLabJText.setVisible(false);
            
          jTextField1.setVisible(false);
          jTextField1.setText("");
          jTextField2.setVisible(false);
          jTextField2.setText("");
          jTextField3.setVisible(false);
          jTextField3.setText("");
          jTextField4.setVisible(false);
          jTextField4.setText("");
          jTextField5.setVisible(false); 
          jTextField5.setText("");
          
        }
    }//GEN-LAST:event_manufacturingComboBoxActionPerformed

    private void processToLabJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processToLabJTextActionPerformed
         
//        LabAssistantWorkAreaJPanel labAssistantWorkAreaJPanel = new LabAssistantWorkAreaJPanel(userProcessContainer, system);
//        userProcessContainer.add("LabAssistantWorkAreaJPanel", labAssistantWorkAreaJPanel);
//        labAssistantWorkAreaJPanel.populateDetails(recyclableWaste);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
        
         //String message = messageJTextField.getText();
        
        LabTestWorkRequest request = new LabTestWorkRequest();
        request.setMessage("message");
        request.setSender(account);
        request.setStatus("Sent");
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof LabOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Request raised to Lab");
        }
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    }//GEN-LAST:event_processToLabJTextActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel17MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JComboBox<String> manufacturingComboBox;
    private javax.swing.JButton processToLabJText;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
